server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/web-services
    username: root
    password: root
    timeBetweenEvictionRunsMillis: 60000
    maxIdle: 1
  main:
    allow-bean-definition-overriding: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  profiles:
    active: prod